In [2]:
from numpy import random
x=random.randint(100)
print(x)

23


In [3]:
from numpy import random
x=random.choice([3,5,7,9])
print(x)

9


In [4]:
from numpy import random
x=random.rand(5)
print(x)

[0.78333132 0.53509019 0.13280523 0.70634538 0.24512209]


In [5]:
from numpy import random
x=random.choice([3,5,7,9],size=(3,5))
print(x)

[[9 9 5 7 7]
 [3 9 5 9 9]
 [5 3 7 7 9]]


In [7]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np
idn=np.eye(3)
print(idn)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
